from flask import Flask #explanation : This line imports the Flask class from the flask module. Flask is a lightweight web framework for Python that allows you to create web applications easily. By importing Flask, we can create an instance of the Flask class and define routes and views for our web application.
import socket #explanation : This line imports the socket module, which provides access to the BSD socket interface. In this code, it is used to retrieve the hostname of the machine (or pod) where the application is running. The hostname can be useful for identifying which instance of the application is responding to requests, especially in a distributed environment like Kubernetes.

app = Flask(__name__) #explanation : This line creates an instance of the Flask class and assigns it to the variable app. The __name__ argument is a special variable in Python that represents the name of the current module. When creating a Flask application, passing __name__ allows Flask to determine the root path of the application, which is useful for locating resources and templates.

@app.route('/') #explanation : This line is a decorator that defines a route for the Flask application. The @app.route('/') decorator tells Flask that the function immediately following it should be called when a user accesses the root URL ("/") of the web application. In this case, when a user visits the root URL, the hello() function will be executed.
def hello(): #explanation : This line defines a function named hello(). This function will be executed when a user accesses the root URL of the web application, as specified by the @app.route('/') decorator. The purpose of this function is to generate and return a response to the user's request.
    hostname = socket.gethostname() #explanation : This line retrieves the hostname of the machine (or pod) where the application is running by calling the gethostname() function from the socket module. The hostname is stored in the variable hostname. This information can be useful for identifying which instance of the application is responding to requests, especially in a distributed environment like Kubernetes.
    return f"Hello from v2 of my Kubernetes application! (Pod: {hostname})\n" #explanation : This line returns a formatted string as the response to the user's request. The string includes a greeting message and the hostname of the machine (or pod) where the application is running. The f-string syntax allows for easy inclusion of variables (in this case, hostname) within the string. When a user accesses the root URL, they will see this message displayed in their web browser.

if __name__ == '__main__': #explanation : This line checks if the current module is being run as the main program. In Python, the __name__ variable is set to '__main__' when the module is executed directly. This conditional statement ensures that the following code block (app.run()) is only executed when the script is run directly, and not when it is imported as a module in another script.
    app.run(host='0.0.0.0', port=5000) #
